# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3877ecbff3bd36e7403f60de122c56698a3d3893dc5117b555477eb897e575f8e8f7aa21867fbb8da94615a476685a536420403e84fde944e700c9f3fba77a04

test:
  secret_key_base: ca0ed704cf0ad751cf6f2bd52f3fad0e2f5338268eae09d1a165356504dc30da012989622fdb381678314723a716ab821ec7e5fb10b11c90a2b002d18d296c71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
